project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!posts/_unorganized/"
  preview:
    port: 4200
    browser: false

execute:
  cache: true
  freeze: auto

website:
  title: "tesshy.com"
  site-url: "https://www.tesshy.com/"
  repo-url: "https://github.com/tesshy/tesshy.github.io"
  repo-branch: main
  # issue-url: "https://github.com/tesshy/tesshy.github.io/issues"
  cookie-consent: 
    type: express
    style: simple
  google-analytics:
    tracking-id: "G-6MV2BD0PZ3"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: pages/index.qmd
        text: Pages
      - href: posts/index.qmd
        text: Posts
      - href: about.ipynb
        text: About

theme:
  light: flatly
  dark: darkly

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



